/**
 * Created by dell on 8/5/2016.
 */
var q = require('q');
var roles = require('../config/role-config.js');

var helper = {};

/*-------------------------------------------------------
 A HELPER METHOD TO CREATE STANDARD USER OBJECT TO BE SENT TO THE CLIENT
 PARAMS:
 [user - User object that contains all the details for the user]
 -------------------------------------------------------*/
helper.createResponseUser = function(user){
    var deferred = q.defer();
    //Make process asynchronous
    process.nextTick(function(){
        var response = {};
        if(user.local){
            response.firstname = user.local.firstname || null;
            response.lastname = user.local.lastname || null;
        }
        response.email = user.email || null;
        response.role = user.role || null;
        response.username = user.username || null;
        response.isActive = user.isActive || null;
        response._id = user._id || null;

        deferred.resolve(response);
    });
    return deferred.promise;
};

/*-------------------------------------------------------
 A HELPER METHOD TO CREATE STANDARD ERROR OBJECT TO BE SENT TO THE CLIENT
 PARAMS:
 [err - err array that contains all the details for the errors]
 [message - a general message if err is not an array]
 -------------------------------------------------------*/
helper.createResponseError = function(err, message){
    var deferred = q.defer();
    //Make process asynchronous
    process.nextTick(function(){
        var response = [];
        //if err is an array of errors generated by validator
        if(err instanceof Array){
            err.forEach(function(err){
                response.push({error: err.msg});
            });
        }
        else{
            response.push({error: message});
        }
        deferred.resolve(response);
    });
    return deferred.promise;
};

/*-------------------------------------------------------
 A HELPER METHOD TO CHECK IF THE USER IS A REGULAR USER OF NOT
 PARAMS:
 [user - User object that contains all the details for the user]
 -------------------------------------------------------*/
helper.isRegularUser = function(user){
    var deferred = q.defer();
    process.nextTick(function(){
        if(user.role.indexOf(roles.admin) > -1 || user.role.indexOf(roles.support) > -1)
            deferred.resolve(false);
        else
            deferred.resolve(true);
    });
    return deferred.promise;
};

module.exports = helper;